version: '2'
services:
  network:
    image: docker.io/kubernetes/pause
    network_mode: "host"
  api:
    image: 10.87.64.33:5043/contrail-analytics-api:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
  collector:
    image: 10.87.64.33:5043/contrail-analytics-collector:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
  alarm-gen:
    image: 10.87.64.33:5043/contrail-analytics-alarm-gen:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
  query-engine:
    image: 10.87.64.33:5043/contrail-analytics-query-engine:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
  snmp-collector:
    image: 10.87.64.33:5043/contrail-analytics-snmp-collector:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
  topology:
    image: 10.87.64.33:5043/contrail-analytics-topology:4.0.0.0-20
    env_file: ../common.env
    network_mode: "service:network"
    volumes:
      - /var/log/docker/contrail:/var/log/contrail
    depends_on:
      - network
